package it.water.connectors.zookeeper.api;

import it.water.core.api.service.BaseApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods and allows interaction with them through a permission system.
 *
 */
public interface ZookeeperConnectorApi extends BaseApi {
    boolean isLeader(String mutexPath);
}