package it.water.connectors.zookeeper.service;

import it.water.connectors.zookeeper.api.ZookeeperConnectorApi;
import it.water.connectors.zookeeper.api.ZookeeperConnectorSystemApi;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.core.service.BaseServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for ZookeeperConnector entity.
 */
@FrameworkComponent
public class ZookeeperConnectorServiceImpl extends BaseServiceImpl implements ZookeeperConnectorApi {

    @Inject
    @Getter
    @Setter
    private ZookeeperConnectorSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    @Override
    //No permission management since no operation is exposed
    public boolean isLeader(String mutexPath) {
        return systemService.isLeader(mutexPath);
    }
}
